### ISSUE TITLE
The first boot doesn't always initialise the MySQL database credentials

### ISSUE THREAD

**Issue by aimxhaisse** [online-labs/image-app-lemp#7]
How to reproduce: boot 5 nodes, out of 5, 2 hadn't their MySQL credentials properly set. I've reviewed the code used to generate credentials, I don't know what's wrong ; I suspect a booting order issue since it's quite random.

**Comment by aimxhaisse** [comment]
More info: MySQL is not always started on the first-boot (thanks to DiscoverY on IRC).

**Comment by ip512** [comment]
same issue

**Comment by aimxhaisse** [comment]
Tested on 16 nodes, it is now OK, the imagehub has been updated with the new image.
